src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email(message="Email inválido")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable()
     */
    private $updated_at;

    // RELACIONAMENTO ENTRE ENTIDADES -----------------------------------
    /**
     * @ORM\OneToMany(targetEntity="Post", mappedBy="author")
     */
    private $posts;

    /**
     * @ORM\Column(type="json")
     */
    private $roles;

    // construtor com array
    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    //getter de 'posts'
    public function getPosts()
    {
        return $this->posts;
    }

    // retornando string para a view
    public function __toString()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    // IMPLEMENTA MÉTODOS DA CLASSE UserInterface (security) ------------
    public function getRoles()
    {
        //$roles = explode(', ', $this->roles);
        //$roles[] = 'ROLE_USER';
        return explode(', ', $this->roles);;
    }

    public function setRoles()
    {
        $this->roles = 'ROLE_AUTHOR';
    }

    public function getUsername(): ?string
    {
        return $this->email; // retorna o identificador do usuário
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    // Nota. Dê uma olhada no App 'Notas' (do mac). Lá tem explicado como foi criado essa classe.
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('email', EmailType::class)
            ->add('username')
            ->add('password', PasswordType::class)
            // Os dados abaixo não precisam aparecer na view, pois serão automáticos
//            ->add('created_at')
//            ->add('updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class, // Esse cara faz um 'bind'(vínculo) do formulário c/ a entidade
        ]);
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
//use http\Env\Request;
use App\service\MailerService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/admin/users", name="user_")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findAll();

        return $this->render('user/index.html.twig', ['users' => $users]);
    }


    /**
     * @Route("/create", name="create")
     */
    public function create(Request $request, UserPasswordEncoderInterface $passwordEncoder, MailerService $mailerService)
    {

        $user = new User(); // cria objeto entity User.
        $form = $this->createForm(UserType::class, $user); // Aqui, criamos o formulário par ser exibido na view
        $form->handleRequest($request); // Para reconhecer se o formulário foi submetido

        if ($form->isSubmitted() && $form->isValid()){
            $user = $form->getData(); // Recebe os dados do formulário via post.

            // encripta a senha do usuário
            $password = $passwordEncoder->encodePassword($user, $user->getPassword()); // pega a senha e usuário
            $user->setPassword($password); // passa a senha para ser encriptada
            $user->setRoles();

            // GRAVANDO NO BANCO DE DADOS
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($user);
            $manager->flush();

            // IMPLEMENTANDO SERVIÇO DO MAILER (envio do email)
            $data['subject'] = '[Blog-sf4] - Usuário criado com sucesso!';
            $data['email'] = $user->getEmail();
            // renderiza uma view especificada
            $view = $this->renderView('email/new_user.html.twig', [
                'name' => $user->getFirstName(),
                'email' => $user->getEmail()
            ]);
            $mailerService->sendMail($data, $view);

            $this->addFlash('success', 'Usuário criado com sucesso!'); // Imprime mensagem para o cliente
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/create.html.twig', [
            'form' => $form->createView() // Manda as informações necessárias para a view ser montada com base nesse objeto
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function edit(Request $request, $id)
    {
        //Busca repositório populado com base no 'id' indicado
        $user = $this->getDoctrine()->getRepository(User::class)->find($id);

        $form = $this->createForm(UserType::class, $user); // Aqui, criamos o formulário par ser exibido na view
        $form->handleRequest($request); // Para reconhecer se o formulário foi submetido

        if ($form->isSubmitted() && $form->isValid()){

            $user = $form->getData(); // Recebe os dados do formulário via post.

            // ATUALIZANDO NO BANCO DE DADOS
            $manager = $this->getDoctrine()->getManager();
            $manager->flush();

            $this->addFlash('success', 'Usuário editado com sucesso!'); // Imprime mensagem para o cliente
            return $this->redirectToRoute('user_edit', ['id' => $id]);
        }

        return $this->render('user/edit.html.twig', [
            'form' => $form->createView() // Manda as informações necessárias para a view ser montada com base nesse objeto
        ]);
    }

    /**
     * @Route("/remove/{id}", name="remove")
     */
    public function remove($id)
    {
        $doctrine = $this->getDoctrine();
        $user = $doctrine->getRepository(User::class)->find($id);

        $manager = $doctrine->getManager(); // Ou... $this->getDoctrine()->getManager()->remove($user);
        $manager->remove($user);
        $manager->flush();

        $this->addFlash('success', 'Usuário removido com sucesso');

        return $this->redirectToRoute('user_index');
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
//use http\Env\Request;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/users", name="user_")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $users = $this->getDoctrine()
                    ->getRepository(User::class)
                    ->findAll();

        return $this->render('user/index.html.twig', ['users' => $users]);
    }


    /**
     * @Route("/create", name="create")
     */
    public function create(Request $request)
    {

        $user = new User(); // cria objeto entity User.
        $form = $this->createForm(UserType::class, $user); // Aqui, criamos o formulário par ser exibido na view
        $form->handleRequest($request); // Para reconhecer se o formulário foi submetido

        if ($form->isSubmitted()){
            $user = $form->getData(); // Recebe os dados do formulário via post.
            $user->setCreatedAt(new \DateTime('now', new \DateTimeZone('America/Recife')));
            $user->setUpdatedAt(new \DateTime('now', new \DateTimeZone('America/Recife')));

            //dump($user); // Esse é um debug do próprio symfony (User é um array com a coleção de dados do formulário.

            // GRAVANDO NO BANCO DE DADOS
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($user);
            $manager->flush();

            $this->addFlash('success', 'Usuário criado com sucesso!'); // Imprime mensagem para o cliente
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/create.html.twig', [
            'form' => $form->createView() // Manda as informações necessárias para a view ser montada com base nesse objeto
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function edit(Request $request, $id)
    {
        //Busca repositório populado com base no 'id' indicado
        $user = $this->getDoctrine()->getRepository(User::class)->find($id);

        $form = $this->createForm(UserType::class, $user); // Aqui, criamos o formulário par ser exibido na view
        $form->handleRequest($request); // Para reconhecer se o formulário foi submetido

        if ($form->isSubmitted()){

            $user = $form->getData(); // Recebe os dados do formulário via post.
            $user->setUpdatedAt(new \DateTime('now', new \DateTimeZone('America/Recife')));

            // ATUALIZANDO NO BANCO DE DADOS
            $manager = $this->getDoctrine()->getManager();
            $manager->flush();

            $this->addFlash('success', 'Usuário editado com sucesso!'); // Imprime mensagem para o cliente
            return $this->redirectToRoute('user_edit', ['id' => $id]);
        }

        return $this->render('user/edit.html.twig', [
            'form' => $form->createView() // Manda as informações necessárias para a view ser montada com base nesse objeto
        ]);
    }

    /**
     * @Route("/remove/{id}", name="remove")
     */
    public function remove($id)
    {
        $doctrine = $this->getDoctrine();
        $user = $doctrine->getRepository(User::class)->find($id);

        $manager = $doctrine->getManager(); // Ou... $this->getDoctrine()->getManager()->remove($user);
        $manager->remove($user);
        $manager->flush();

        $this->addFlash('success', 'Usuário removido com sucesso');

        return $this->redirectToRoute('user_index');
    }
}

templates/user/create.html.twig
{#
    AS FORMATAÇÕES EM CSS ESTÃO VINDO DE UM LINK CSS EM: 'base.html'
    E TAMBÉM DO TEMPLATE EM config/packages/twig.yaml

        Os alertas estão vindo de templates/includes/messages.html.twig, incluído em base.html.twig
 #}

{% extends 'base_admin.html.twig' %}

{% block title %}Criar Usuário{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
        <h2>Criação do Usuário</h2>
        <hr>
    {# A vriável 'form' abaixo veio da classe 'UserController' #}
    {{ form_start(form, {attr: {novalidate: "novalidate"}}) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-lg btn-success">Cadastrar Usuário</button> {# A dica é criar o botão de envio aqui, como foi feiro, e não na classe #}
    {{ form_end(form) }}
</div>
{% endblock %}

templates/user/edit.html.twig
{#
    AS FORMATAÇÕES EM CSS ESTÃO VINDO DE UM LINK CSS EM: 'base.html'
    E TAMBÉM DO TEMPLATE EM config/packages/twig.yaml

    Os alertas estão vindo de templates/includes/messages.html.twig, incluído em base.html.twig
 #}

{% extends 'base_admin.html.twig' %}

{% block title %}Edição de Usuário!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
        <h2>Edição do Usuário</h2>
        <hr>
    {# A vriável 'form' abaixo veio da classe 'UserController' #}
    {{ form_start(form, {attr: {novalidate: "novalidate"}}) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-lg btn-success">Atualizar Usuário</button> {# A dica é criar o botão de envio aqui, como foi feiro, e não na classe #}
    {{ form_end(form) }}
</div>
{% endblock %}

templates/user/index.html.twig
{#
    AS FORMATAÇÕES EM CSS ESTÃO VINDO DE UM LINK CSS EM: 'base.html'
    E TAMBÉM DO TEMPLATE EM config/packages/twig.yaml

    Os alertas estão vindo de templates/includes/messages.html.twig, incluído em base.html.twig
 #}

{% extends 'base_admin.html.twig' %}

{% block body %}
    <h1>Usuários</h1>

    {# Os estilos css estão vindo da 'base.twig.html', de um link copiado do site bootstrap #}
    <a href="{{ path('user_create') }}" class="btn btn-sm btn-success">Criar Usuário</a>
    <hr>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>Email</th>
            <th>Criado em</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        {# Esse laço faz uma varredura par buscar todos os usuários #}
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.createdAt|date('d/m/Y H:i:s') }}</td>
                <td>
                    <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-sm btn-primary">Editar</a>
                    <a href="{{ path('user_remove', {'id': user.id}) }}" class="btn btn-sm btn-danger">Remover</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
{% endblock %}

{% block title %}
    Usuários
{% endblock %}